"""initial schema

Revision ID: a636bfbfbcdf
Revises: 
Create Date: 2026-08-13 10:36:52.179398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision: str = 'a636bfbfbcdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tool_access', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('output_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_agents_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('name', name=op.f('uq_agents_name'))
    )
    op.create_index(op.f('ix_agents_org_id'), 'agents', ['org_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('dns_name', sa.String(length=255), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('exposure', sa.String(length=32), nullable=False),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assets_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_dns_name'), 'assets', ['dns_name'], unique=False)
    op.create_index(op.f('ix_assets_exposure'), 'assets', ['exposure'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('hash_chain', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_logs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('mitre', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('logic', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('false_positive_notes', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('regression_test', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_detection_rules_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_rules'))
    )
    op.create_index(op.f('ix_detection_rules_org_id'), 'detection_rules', ['org_id'], unique=False)
    op.create_index(op.f('ix_detection_rules_rule_id'), 'detection_rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_detection_rules_status'), 'detection_rules', ['status'], unique=False)
    op.create_table('engagements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('approved_by', sa.String(length=32), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_engagements_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engagements'))
    )
    op.create_index(op.f('ix_engagements_org_id'), 'engagements', ['org_id'], unique=False)
    op.create_index(op.f('ix_engagements_status'), 'engagements', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assignee_id', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('attack_techniques', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('affected_assets', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('affected_users', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('related_findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ai_analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remediation_notes', sa.Text(), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_incidents_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_org_id'), 'incidents', ['org_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_notifications_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('triggers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_playbooks_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbooks'))
    )
    op.create_index(op.f('ix_playbooks_org_id'), 'playbooks', ['org_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_policies_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index(op.f('ix_policies_org_id'), 'policies', ['org_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_reports_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_org_id'), 'reports', ['org_id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_teams_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_org_id'), 'teams', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_runs_agent_id_agents')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_agent_runs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_table('asset_relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('source_asset_id', sa.String(length=32), nullable=False),
    sa.Column('target_asset_id', sa.String(length=32), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_asset_relationships_org_id_organizations')),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], name=op.f('fk_asset_relationships_source_asset_id_assets')),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], name=op.f('fk_asset_relationships_target_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_relationships'))
    )
    op.create_index(op.f('ix_asset_relationships_org_id'), 'asset_relationships', ['org_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_relationship_type'), 'asset_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_asset_relationships_source_asset_id'), 'asset_relationships', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_target_asset_id'), 'asset_relationships', ['target_asset_id'], unique=False)
    op.create_table('attack_paths',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_asset_id', sa.String(length=32), nullable=True),
    sa.Column('target_asset_id', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_asset_id'], ['assets.id'], name=op.f('fk_attack_paths_entry_asset_id_assets')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_attack_paths_org_id_organizations')),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], name=op.f('fk_attack_paths_target_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attack_paths'))
    )
    op.create_index(op.f('ix_attack_paths_org_id'), 'attack_paths', ['org_id'], unique=False)
    op.create_index(op.f('ix_attack_paths_risk_score'), 'attack_paths', ['risk_score'], unique=False)
    op.create_index(op.f('ix_attack_paths_status'), 'attack_paths', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_events_asset_id_assets')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_events_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_asset_id'), 'events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_events_dedup_hash'), 'events', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_org_id'), 'events', ['org_id'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('cve', sa.String(length=64), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('exploitability', sa.String(length=16), nullable=False),
    sa.Column('business_impact', sa.String(length=512), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('attack_path_relevant', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ai_triage', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets')),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_findings_engagement_id_engagements')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_findings_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_cve'), 'findings', ['cve'], unique=False)
    op.create_index(op.f('ix_findings_cwe'), 'findings', ['cwe'], unique=False)
    op.create_index(op.f('ix_findings_dedup_key'), 'findings', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_findings_engagement_id'), 'findings', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_findings_org_id'), 'findings', ['org_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_source'), 'findings', ['source'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identity_type', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('privileged', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_identities_asset_id_assets')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_identities_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identities'))
    )
    op.create_index(op.f('ix_identities_asset_id'), 'identities', ['asset_id'], unique=False)
    op.create_index(op.f('ix_identities_org_id'), 'identities', ['org_id'], unique=False)
    op.create_table('incident_timeline_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_timeline_entries_incident_id_incidents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_timeline_entries'))
    )
    op.create_index(op.f('ix_incident_timeline_entries_incident_id'), 'incident_timeline_entries', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_entries_timestamp'), 'incident_timeline_entries', ['timestamp'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('target_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('logs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('worker', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_jobs_engagement_id_engagements')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_jobs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_engagement_id'), 'jobs', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('response_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('playbook_id', sa.String(length=32), nullable=True),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=32), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by', sa.String(length=32), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_response_actions_incident_id_incidents')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_response_actions_org_id_organizations')),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], name=op.f('fk_response_actions_playbook_id_playbooks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_actions'))
    )
    op.create_index(op.f('ix_response_actions_incident_id'), 'response_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_response_actions_org_id'), 'response_actions', ['org_id'], unique=False)
    op.create_index(op.f('ix_response_actions_playbook_id'), 'response_actions', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_response_actions_risk_level'), 'response_actions', ['risk_level'], unique=False)
    op.create_index(op.f('ix_response_actions_status'), 'response_actions', ['status'], unique=False)
    op.create_table('scope_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_scope_rules_engagement_id_engagements')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_scope_rules_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_rules'))
    )
    op.create_index(op.f('ix_scope_rules_engagement_id'), 'scope_rules', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_scope_rules_org_id'), 'scope_rules', ['org_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_services_asset_id_assets')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_services_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_asset_id'), 'services', ['asset_id'], unique=False)
    op.create_index(op.f('ix_services_org_id'), 'services', ['org_id'], unique=False)
    op.create_table('technologies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_technologies_asset_id_assets')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_technologies_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technologies'))
    )
    op.create_index(op.f('ix_technologies_asset_id'), 'technologies', ['asset_id'], unique=False)
    op.create_index(op.f('ix_technologies_org_id'), 'technologies', ['org_id'], unique=False)
    op.create_table('user_teams',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_user_teams_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_teams_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'team_id', name=op.f('pk_user_teams'))
    )
    op.create_table('attack_path_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('attack_path_id', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_attack_path_nodes_asset_id_assets')),
    sa.ForeignKeyConstraint(['attack_path_id'], ['attack_paths.id'], name=op.f('fk_attack_path_nodes_attack_path_id_attack_paths')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attack_path_nodes'))
    )
    op.create_index(op.f('ix_attack_path_nodes_attack_path_id'), 'attack_path_nodes', ['attack_path_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('finding_id', sa.String(length=32), nullable=True),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_evidence_engagement_id_engagements')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_evidence_finding_id_findings')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_evidence_incident_id_incidents')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_evidence_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_org_id'), 'evidence', ['org_id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('finding_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verification', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_remediations_finding_id_findings')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_remediations_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediations'))
    )
    op.create_index(op.f('ix_remediations_finding_id'), 'remediations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediations_org_id'), 'remediations', ['org_id'], unique=False)
    op.create_table('retests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('finding_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('before_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('after_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_ref', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_retests_finding_id_findings')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_retests_job_id_jobs')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_retests_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retests'))
    )
    op.create_index(op.f('ix_retests_finding_id'), 'retests', ['finding_id'], unique=False)
    op.create_index(op.f('ix_retests_org_id'), 'retests', ['org_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('engagement_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_scans_engagement_id_engagements')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_scans_job_id_jobs')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_scans_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index(op.f('ix_scans_org_id'), 'scans', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_org_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_retests_org_id'), table_name='retests')
    op.drop_index(op.f('ix_retests_finding_id'), table_name='retests')
    op.drop_table('retests')
    op.drop_index(op.f('ix_remediations_org_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_finding_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_evidence_org_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_attack_path_nodes_attack_path_id'), table_name='attack_path_nodes')
    op.drop_table('attack_path_nodes')
    op.drop_table('user_teams')
    op.drop_index(op.f('ix_technologies_org_id'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_asset_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_services_org_id'), table_name='services')
    op.drop_index(op.f('ix_services_asset_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_scope_rules_org_id'), table_name='scope_rules')
    op.drop_index(op.f('ix_scope_rules_engagement_id'), table_name='scope_rules')
    op.drop_table('scope_rules')
    op.drop_index(op.f('ix_response_actions_status'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_risk_level'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_playbook_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_org_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_incident_id'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_engagement_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_incident_timeline_entries_timestamp'), table_name='incident_timeline_entries')
    op.drop_index(op.f('ix_incident_timeline_entries_incident_id'), table_name='incident_timeline_entries')
    op.drop_table('incident_timeline_entries')
    op.drop_index(op.f('ix_identities_org_id'), table_name='identities')
    op.drop_index(op.f('ix_identities_asset_id'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_source'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_org_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_engagement_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_dedup_key'), table_name='findings')
    op.drop_index(op.f('ix_findings_cwe'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_org_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_dedup_hash'), table_name='events')
    op.drop_index(op.f('ix_events_asset_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_attack_paths_status'), table_name='attack_paths')
    op.drop_index(op.f('ix_attack_paths_risk_score'), table_name='attack_paths')
    op.drop_index(op.f('ix_attack_paths_org_id'), table_name='attack_paths')
    op.drop_table('attack_paths')
    op.drop_index(op.f('ix_asset_relationships_target_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_source_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_relationship_type'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_org_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_org_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_org_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_policies_org_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_playbooks_org_id'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_org_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_engagements_status'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_org_id'), table_name='engagements')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_detection_rules_status'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_rule_id'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_org_id'), table_name='detection_rules')
    op.drop_table('detection_rules')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_exposure'), table_name='assets')
    op.drop_index(op.f('ix_assets_dns_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_agents_org_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
